Feature topic 6.2.1
nikolajew-a-a/-internshipAndersen pull request #23
Opened 2020-10-06 09:53 UTC by nikolajew-a-a

6.2. Переписать приложения News Service (https://jira.andersenlabcom/browse/FAT-4803) с использованием Moxy https://habr.com/ru/post/276189/

2020-10-06 16:18 UTC, Akvit requested changes

2020-10-06 18:47 UTC, nikolajew-a-a commented on Topic 6 1/app/src/main/java/com/example/android/topic61/data/Theme.java
> +public class Theme {
Имеется ввиду категория - в этом классе хранятся категории (темы) новостей, которые пользователь может выбрать для просмотра

2020-10-07 23:10 UTC, Akvit requested changes

2020-10-07 23:10 UTC, Akvit commented on Topic 6 1/app/src/main/java/com/example/android/topic61/model/MainModel.java
> +    MainPresenter presenter;
- [ ] private+ плюс, надо, чтобы в поле был интерфейс, а не сам класс

2020-10-07 23:10 UTC, Akvit commented on Topic 6 1/app/src/main/java/com/example/android/topic61/presenter/MainPresenter.java
> +    private MainModel model;
- [ ] Должен быть интерфейс, а не класс

2020-10-08 09:06 UTC, merged