Feature topic 8.1.1
nikolajew-a-a/-internshipAndersen pull request #26
Opened 2020-10-14 18:15 UTC by nikolajew-a-a

8.1. Переписать приложение News Service (Разработанное в задании к Теме 4) с использованием RxPM и Architecture Components. Retrofit не работает напрямую с LiveData, способы решения есть здесь https://medium.com/@pivincii/using-retrofit-with-livedata-5c5a49544ba3
    8.3. Данные, полученные из сети, кэшировать в БД на одну минуту с помощью Room.

2020-10-15 16:26 UTC, Akvit requested changes

2020-10-17 20:59 UTC, Akvit requested changes

2020-10-17 20:59 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/repository/ArticlesRepository.java
> +    public void setStateLoading() {
- [ ] репозиторий, даже через вью модел, не может управлять активити. репозитрий тупо делает запросы в сеть, или бд. исходя из этого, вью модел решает будет ли активити отображать прогресс бар, или нет

2020-10-17 20:59 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/view/MainActivity.java
> +    LiveData<List<Article>> articlesLiveData;
- [ ] зачем это здесь?

2020-10-17 20:59 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/view/MainActivity.java
> +    ArticlesViewModel model;
- [ ] private

2020-10-17 20:59 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/view/MainActivity.java
> +
- [ ] зачем такой отступ? это не красиво. лучше убери

2020-10-17 20:59 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/view/adapter/GlideAdapter.java
> +public class GlideAdapter {
- [ ] GlideBindingAdapter

2020-10-17 20:59 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/view/adapter/PicassoAdapter.java
> +public class PicassoAdapter {
- [ ] PicassoBindingAdapter. И лучше объединить эти классы

2020-10-17 20:59 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/view/MainActivity.java
> +        model.getArticles().observe(MainActivity.this, new Observer<List<Article>>() {
- [ ] лямбды везде

2020-10-17 20:59 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +
в активити можно написать вот так model. getErrorMessageTemp(), что не хорошо с тз инкапсуляции

- [ ] убери мутабельные live data из общего доступа
- [ ] реализуй сохранение данных и их переиспользование при повороте. зачем же тебе вью модель тода?

2020-10-17 20:59 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/view/adapter/GlideAdapter.java
> +    @BindingAdapter("glide")
- [ ] скачивание картинок не работает чет

2020-10-19 10:21 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +    public void setStateLoading() {
- [ ] все 3 метода ниже private

2020-10-19 10:21 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/view/adapter/GlideAdapter.java
> +public class GlideAdapter {
Точно сделал?

2020-10-19 10:21 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/view/adapter/PicassoAdapter.java
> +public class PicassoAdapter {
У меня пока старая версия

2020-10-19 10:24 UTC, Akvit requested changes

2020-10-19 10:24 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +
- [ ] лишний отступ

2020-10-19 10:24 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +
- [ ] лишний отступ

2020-10-19 10:32 UTC, Akvit requested changes

2020-10-19 10:32 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +
а в чём разница между этими 2 методами? На первый взгляд лишняя логика

2020-10-19 10:32 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +
Покажи где у тебя сохранение реализовано?

2020-10-19 10:44 UTC, Akvit requested changes

2020-10-19 10:44 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/view/MainActivity.java
> +                message.setVisibility(View.VISIBLE);
- [ ] просто выведи тоаст. не усложняй

2020-10-19 10:44 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/view/MainActivity.java
> +            if (showArticlesState) {
- [ ] эта логика должна находиться в секции isLoading

2020-10-19 11:23 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +
loadArticlesFirstTime выполнялся, если была выполнена инициализация спиннера. Метод Загружал список новостей, если до этого viewModel не существовала (т.е. при запуске приложения) и не загружал, если viewModel существовала (переворот экрана).
loadArticlesNextTime выполнялся, если был выбрана новая категория и была выполнена инициализация. Метод всегда загружал список новостей.

Но сейчас я объединил эти методы и сделал проще

2020-10-19 12:20 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +
У меня состояние сохранено во вью модель. При повороте экрана у меня нет запроса на обновление данных и соответственно покажутся старые данные, которые хранятся во ViewModel.
Запроса на обновление при повороте экрана не будет, т.к. я учел переворот экрана в методе loadArticles(String theme, boolean isSpinnerInit)

2020-10-20 20:33 UTC, merged