Feature topic 8.4.1
nikolajew-a-a/-internshipAndersen pull request #27
Opened 2020-10-21 14:50 UTC by nikolajew-a-a

8.4. Написать тесты на ViewModel и Model, если второй выделен в отдельный слой, на бины с данными тесты писать не нужно.

2020-10-21 19:37 UTC, Akvit requested changes

2020-10-21 19:37 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/network/Network.java
> +    public void setJsonPlaceHolderApi(JsonPlaceHolderApi jsonPlaceHolderApi) {
нет-нет-нет. Это внутренняя кухня. убери сеттеры. даже, если для тестирования. Ты мокаешь объекты, которые передаются в конструктор и с помощью манипуляций над ними, ты тестируешь внутренний функционал
- [ ] убери

2020-10-21 19:37 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/repository/ArticlesRepository.java
> +
- [ ] то же самое

2020-10-21 19:37 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +        this.repository = repository;
- [ ] убери

2020-10-21 19:37 UTC, Akvit commented on Topic 4 1/app/src/test/java/com/example/android/model/CacheTest.java
> +    ArticlesDatabase database;
- [ ] private всё

2020-10-21 19:37 UTC, Akvit commented on Topic 4 1/app/src/test/java/com/example/android/model/CacheTest.java
> +
- [ ] у тебя все классы, кроме тестируемого должны быть моками

2020-10-22 12:08 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/network/Network.java
> +    public void setJsonPlaceHolderApi(JsonPlaceHolderApi jsonPlaceHolderApi) {
Будет исправлено при выполнении заданий темы 10.

2020-10-22 12:08 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/repository/ArticlesRepository.java
> +
Будет исправлено при выполнении заданий темы 10.

2020-10-22 12:08 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +        this.repository = repository;
Будет исправлено при выполнении заданий темы 10.

2020-10-22 12:08 UTC, nikolajew-a-a commented on Topic 4 1/app/src/test/java/com/example/android/model/CacheTest.java
> +
Будет исправлено при выполнении заданий темы 10.

2020-10-22 19:36 UTC, Akvit requested changes

2020-10-22 19:36 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +
- [ ] нижние самые 3 метода:
всё таки, там логика какая-то избыточная. лучше активити просто говорить, что идёт загрузка или загрузка завершена, а активити сама решит, что ей прятать, а что показывать

2020-10-22 19:36 UTC, Akvit commented on Topic 4 1/app/src/test/java/com/example/android/model/CacheTest.java
> +    public void CacheTestAfter() {
- [ ] с маленькой

2020-10-25 18:04 UTC, Akvit requested changes

2020-10-25 18:04 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +        isLoadingState.setValue(true);
- [ ] Почему ты показываешь загрузку? Ты же сейчас ничего не скачиваешь. Перенеси это в метод загрузки

2020-10-25 19:38 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/viewmodel/ArticlesViewModel.java
> +        isLoadingState.setValue(true);
Я добавил установку значения в конструктор, чтобы инициализировать переменную. Сейчас удалил из конструктора и устанавливаю значение по умолчанию при создании переменной.
В методе загрузки переменная меняет свое значение

2020-10-26 09:16 UTC, merged