Feature topic 10.3.1
nikolajew-a-a/-internshipAndersen pull request #28
Opened 2020-10-27 10:00 UTC by nikolajew-a-a

10.3. Переписать приложение News Service (можно использовать версию на MVVM) (https://jira.andersenlab.com/browse/FAT-4803) согласно требованиям к слоям и классам Clean Architecture.
    10.4. Используя Dagger2, внедрить через @Inject зависимость в активити/фрагмент от библиотеки загрузки изображений (Glide или Picasso) и Retrofit там, где они непосредственно используются, а также Presenter/ViewModel (на выбор).

2020-10-29 11:31 UTC, Akvit requested changes

2020-10-29 11:31 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/data/repository/ArticlesRepository.java
> +import com.example.android.topic41.presentation.viewmodel.ArticlesViewModelInterface;
- [ ] импорт презентейшена не должен быть в дата слое

2020-10-29 11:31 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/di/modules/ArticlesViewModelModule.java
> +        return new ArticlesViewModel(repository);
- [ ] постой. а как это ты на прямую создаёшь вью модель? 
https://medium.com/better-programming/everything-to-understand-about-viewmodel-400e8e637a58

2020-10-29 13:59 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/data/repository/ArticlesRepository.java
> +import com.example.android.topic41.presentation.viewmodel.ArticlesViewModelInterface;
ArticlesViewModelInterface перенес в data.repository и переименовал в RepositoryCallbackInterface

2020-10-29 14:01 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/di/modules/ArticlesViewModelModule.java
> +        return new ArticlesViewModel(repository);
Исправил, теперь получаю ViewModel  с помощью ViewModelProvider

2020-10-30 08:37 UTC, Akvit requested changes

2020-10-30 08:37 UTC, Akvit commented on Topic 4 1/app/build.gradle
> +//    implementation "com.google.dagger:dagger-android-support:2.26"
- [ ] комменты убери

2020-10-30 08:37 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/di/modules/ArticlesViewModelModule.java
> +        return new ViewModelProvider((ViewModelStoreOwner) activity, new ViewModelProviderFactory(repository)).get(ArticlesViewModel.class);
- [ ] на реальном проекте могут прикопаться к слишком длинной строке. так что перенеси лучше

2020-10-30 13:02 UTC, Akvit requested changes

2020-10-30 13:02 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/presentation/view/MainActivity.java
> +        AppComponent component = DaggerAppComponent.builder().application(getApplication()).activity(this).build();
- [ ] спрячь инициалтзацию в application

2020-11-02 13:35 UTC, Akvit requested changes

2020-11-02 13:35 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/presentation/view/adapter/Adapter.java
> +import com.example.android.topic41.data.util.Article;
- [ ] никаких импортов из дата слоя в презентационный. Лучше дата классы в доменный слой перенеси

2020-11-02 13:35 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/di/modules/DataBaseModule.java
> +        //return Room.databaseBuilder(application, ArticlesDatabase.class, "database").build();
- [ ] убери этот коммент

2020-11-02 13:35 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/presentation/view/MainActivity.java
> +                .appComponent(((BaseApplication) getApplication()).getAppComponent())
- [ ] BaseApplication.getComponent()

2020-11-03 11:58 UTC, Akvit requested changes

2020-11-03 11:58 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/presentation/view/MainActivity.java
>      boolean isInit = true;
- [ ] перенеси bool во viewModel

2020-11-03 11:58 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/data/network/Network.java
>          Retrofit retrofit = new Retrofit.Builder()
по-хорошему, ретрофит тоже надо провайдить)

2020-11-03 12:16 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/data/network/Network.java
>          Retrofit retrofit = new Retrofit.Builder()
Подправил

2020-11-03 12:38 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/presentation/view/MainActivity.java
>      boolean isInit = true;
Перенес во ViewModel и переименовал в isInitializedActivity

2020-11-03 13:07 UTC, merged