Feature topic 10.5.1
nikolajew-a-a/-internshipAndersen pull request #29
Opened 2020-11-03 13:54 UTC by nikolajew-a-a

10.5. Используя RxJava2 (изучить https://habr.com/ru/company/badoo/blog/328434/), получить при сетевом запросе Observable<Response>, сразу при получении отфильтровать новости, чей title длиннее 20 символов, и добавить (через map) в каждый title слово Filtered.

2020-11-04 09:24 UTC, Akvit requested changes

2020-11-04 09:24 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/data/network/Network.java
> +                        Log.i("mLog", "Удачный запрос");
- [ ] убери отсюда подписку

- [ ] убери коллбэки

- [ ] весь маппинг и прочую логику в домен

2020-11-04 09:24 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/data/network/JsonPlaceHolderApi.java
> +    Observable<Response<News>> getNews(@QueryMap Map<String, String> parameters);
- [ ] Single<List<News>>

2020-11-04 09:24 UTC, Akvit commented on Topic 4 1/app/build.gradle
> +
- [ ] выпили асинктаски отовсюду

2020-11-04 19:18 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/data/network/Network.java
> +                        Log.i("mLog", "Удачный запрос");
Перенес добавление слова "Filtered" (маппинг) в домен

2020-11-05 08:05 UTC, Akvit requested changes

2020-11-05 13:38 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/data/repository/ArticlesRepository.java
> +    private Single<List<Article>> observable;
объяви эту переменнкю в createObservable()

2020-11-05 13:44 UTC, Akvit commented on Topic 4 1/app/src/main/java/com/example/android/topic41/data/network/Network.java
> +                        Log.i("mLog", "Удачный запрос");
modifyResponse() тоже туда. Иногда, маппингом занимается отдельная сущность, но мы это оставим
subscribeOn не перенёс

2020-11-05 14:00 UTC, Akvit requested changes

2020-11-06 10:12 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/data/repository/ArticlesRepository.java
> +    private Single<List<Article>> observable;
Удалил эту переменную, теперь она не используется

2020-11-06 10:27 UTC, nikolajew-a-a commented on Topic 4 1/app/src/main/java/com/example/android/topic41/data/network/Network.java
> +                        Log.i("mLog", "Удачный запрос");
В repository map используется map для записи в бд - метод разделил на два более "говорящих". В Network оставил map, который только из News получает List<Article>

2020-11-06 14:07 UTC, merged