Feature topic 10.6.1
nikolajew-a-a/-internshipAndersen pull request #30
Opened 2020-11-06 16:44 UTC by nikolajew-a-a

10.6. Написать Unit-тесты на основной функционал Domain и Data слоев приложения.

2020-11-09 06:01 UTC, Akvit requested changes

2020-11-09 06:01 UTC, Akvit commented on Topic 4 1/app/src/test/java/com/example/android/data/CacheTest.java
> +        Context context = ApplicationProvider.getApplicationContext();
- [ ] mock

2020-11-09 06:01 UTC, Akvit commented on Topic 4 1/app/src/test/java/com/example/android/data/NetworkTest.java
> +        Retrofit retrofit = new Retrofit.Builder().baseUrl(BASE_URL)
- [ ] mock

2020-11-10 10:11 UTC, nikolajew-a-a commented on Topic 4 1/app/src/test/java/com/example/android/data/CacheTest.java
> +        Context context = ApplicationProvider.getApplicationContext();
Замокал database и articleDao, поэтому context стал не нужным и я его удалил

2020-11-10 10:19 UTC, nikolajew-a-a commented on Topic 4 1/app/src/test/java/com/example/android/data/NetworkTest.java
> +        Retrofit retrofit = new Retrofit.Builder().baseUrl(BASE_URL)
Переделал конструктор Network - теперь вместо Retrofit передается JsonPlaceHolderApi.
JsonPlaceHolderApi замокал.

2020-11-10 10:29 UTC, Akvit requested changes

2020-11-10 10:29 UTC, Akvit commented on Topic 4 1/app/src/test/java/com/example/android/data/CacheTest.java
> +@RunWith(AndroidJUnit4.class)
- [ ] удали. это для инструментальных тестов

2020-11-10 10:29 UTC, Akvit commented on Topic 4 1/app/src/test/java/com/example/android/data/NetworkTest.java
> +@RunWith(AndroidJUnit4.class)
- [ ] удали. это для инструментальных тестов

2020-11-10 10:29 UTC, Akvit commented on Topic 4 1/app/src/test/java/com/example/android/data/RepositoryTest.java
> +@RunWith(AndroidJUnit4.class)
- [ ] удали. это для инструментальных тестов

2020-11-10 10:29 UTC, Akvit commented on Topic 4 1/app/src/test/java/com/example/android/domain/SingleUseCaseTest.java
> +@RunWith(AndroidJUnit4.class)
- [ ] удали. это для инструментальных тестов

2020-11-10 13:27 UTC, merged